### ISSUE TITLE
Quick question and a security issue?

### ISSUE THREAD

**Issue by Aptronymist** [shakibyzn/image-time-classifier-app#1]
I was looking for something to handle classification similar to this, could I not just change the labels from time of day to any arbitrary thing and use it to classify photos?

also, I saw this, not sure if it's valid but you might want to change it.

![image](https://github.com/shakibyzn/image-time-classifier-app/assets/108482020/4c7e50a7-2896-4b3f-8f35-53b82f350a55)

**Comment by shakibyzn** [comment]
Yes, you can. You might not get a perfect performance in some cases though. You can also fine-tune the CLIP model on your dataset to improve the performance.
